version: "3.1"
services:
  master:
    image: ajeetraina/jmeter-master
    tty: true
    ports:
      - "60000"
    networks:
      - jm-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      placement:
          constraints: [node.role == manager]
  slave:
    image: ajeetraina/jmeter-server
    tty: true
    networks:
      - jm-network
    ports:
      - "50000"
      - "1099"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.role == worker]
networks:
  jm-network:
